CREATE DATABASE  IF NOT EXISTS `Analytics` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `Analytics`;

CREATE TABLE `InstanceTbl` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `DateTime` text NOT NULL,
  `License` text NOT NULL,
  `PCName` text NOT NULL,
  `ProgramCode` text NOT NULL,
  `ProgramVersion` int(11) NOT NULL,
  `ProgramRelease` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SurveyTbl` (
  `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `InstanceID` INT UNSIGNED NOT NULL, 
  `Command` TEXT NOT NULL, 
  `Count` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `TerrainTbl` (
  `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `InstanceID` INT UNSIGNED NOT NULL, 
  `Command` TEXT NOT NULL, 
  `Count` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `RoadTbl` (
  `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `InstanceID` INT UNSIGNED NOT NULL, 
  `Command` TEXT NOT NULL, 
  `Count` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
     
CREATE TABLE `SewerTbl` (
  `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `InstanceID` INT UNSIGNED NOT NULL, 
  `Command` TEXT NOT NULL, 
  `Count` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `StormTbl` (
  `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `InstanceID` INT UNSIGNED NOT NULL, 
  `Command` TEXT NOT NULL, 
  `Count` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `WaterTbl` (
  `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `InstanceID` INT UNSIGNED NOT NULL, 
  `Command` TEXT NOT NULL, 
  `Count` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SignageTbl` (
  `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `InstanceID` INT UNSIGNED NOT NULL, 
  `Command` TEXT NOT NULL, 
  `Count` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
